// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gufranmirza/ticker-api/web/router (interfaces: Router)

// Package routermock is a generated GoMock package.
package routermock

import (
	chi "github.com/go-chi/chi"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRouter is a mock of Router interface
type MockRouter struct {
	ctrl     *gomock.Controller
	recorder *MockRouterMockRecorder
}

// MockRouterMockRecorder is the mock recorder for MockRouter
type MockRouterMockRecorder struct {
	mock *MockRouter
}

// NewMockRouter creates a new mock instance
func NewMockRouter(ctrl *gomock.Controller) *MockRouter {
	mock := &MockRouter{ctrl: ctrl}
	mock.recorder = &MockRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRouter) EXPECT() *MockRouterMockRecorder {
	return m.recorder
}

// Router mocks base method
func (m *MockRouter) Router(arg0 bool) *chi.Mux {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Router", arg0)
	ret0, _ := ret[0].(*chi.Mux)
	return ret0
}

// Router indicates an expected call of Router
func (mr *MockRouterMockRecorder) Router(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Router", reflect.TypeOf((*MockRouter)(nil).Router), arg0)
}
