// Package api configures an http server for administration and application resources.

package router

import (
	"time"

	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
	"github.com/go-chi/render"
	_ "github.com/gufranmirza/ticker-api/web/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/gufranmirza/ticker-api/web/middlewares"
	"github.com/gufranmirza/ticker-api/web/services/health"
	"github.com/gufranmirza/ticker-api/web/services/v1/tradesservice"
	swagger "github.com/swaggo/http-swagger"

	"github.com/spf13/viper"
)

type router struct {
	health      health.Health
	trades      tradesservice.TradesService
	middlewares middlewares.Middlewares
}

// NewRouter returns the router implementation
func NewRouter() Router {
	return &router{
		health:      health.NewHealth(),
		middlewares: middlewares.NewMiddlewares(),
		trades:      tradesservice.NewTradesService(),
	}
}

// Router configures application resources and routes.
func (router *router) Router(enableCORS bool) *chi.Mux {
	// v1 URL router prefix
	v1Prefix := viper.GetString("web.url_prefix") + viper.GetString("web.api_version_v1")

	// ==================== Public Router ======================
	r := chi.NewRouter()
	r.Use(middleware.Recoverer)
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)
	r.Use(middleware.Timeout(time.Duration(viper.GetInt("web.request_timeout_in_sec")) * time.Second))

	// set up logging
	r.Use(router.middlewares.Logger())
	// settin up content-type
	r.Use(render.SetContentType(render.ContentTypeJSON))
	// use CORS middleware if client is not served by this api, e.g. from other domain or CDN
	if enableCORS {
		r.Use(corsConfig().Handler)
	}

	// =================  health routes ======================
	r.Get(v1Prefix+"/health", router.health.GetHealth)

	// ================= API Documentation ====================
	if viper.GetBool("web.show_api_docs") {
		r.Get(v1Prefix+"/swagger/*", swagger.Handler())
	}

	// ================= Trades ====================
	r.Post(v1Prefix+"/trades/buy"+"/{ticker_symbol}", router.trades.Create)
	r.Get(v1Prefix+"/trades/buy"+"/{ticker_symbol}", router.trades.Get)

	return r
}
